on:
  release:
    types:
      - published
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Installing Node.js v16
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
      - run: |
          git fetch origin main
          git checkout main
      - run: npm install
      - run: npm run build
      - name: Publish source
        run: |
          npm publish --access public || true
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'