on:
  release:
    types:
      - published
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
      - run: |
          git fetch origin main
          git checkout main
      - run: npm install
      - run: npm run build
      - run: npm run build:typings
      - name: Publish source
        run: |
          npm publish --access public || true
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'